name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 16 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: base
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/base.svg
          token: ${{ secrets.MY_TOKEN }}
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/metrics.plugin.achievements.compact.svg
          token: ${{ secrets.MY_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.MY_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.MY_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Recently starred
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/metrics.plugin.stars.svg
          token: ${{ secrets.MY_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
